# Site Settings
url: "https://dasabodha.omnnbc.in"
baseurl: ""

# Sitemap Settings
sitemap:
  output: "sitemap.xml"
  # Include folders where your content actually lives
  include_folders:
    - posts
    - pages
  # Files to stay out of search results
  exclude:
    - node_modules
    - package.json
    - package-lock.json
    - generate-sitemap.js
    - .github
    - .git
    - assets/css
    - assets/js
