<?php 
include __DIR__ . '/protect.php'; // global copy protection 
include __DIR__ . '/header.php'; 

// Load posts
$postsFile = __DIR__ . '/data/posts.json';
$posts = file_exists($postsFile) ? json_decode(file_get_contents($postsFile), true) : [];

// Filter public posts
$posts = array_filter($posts, fn($p) => ($p['status'] ?? '') === 'public');

// Sort by newest first
usort($posts, fn($a, $b) => strtotime($b['created'] ?? '1970-01-01') - strtotime($a['created'] ?? '1970-01-01'));

// Pagination setup
$postsPerPage = 10;
$totalPosts = count($posts);
$totalPages = ceil($totalPosts / $postsPerPage);
$currentPage = isset($_GET['page']) ? max(1, intval($_GET['page'])) : 1;
$offset = ($currentPage - 1) * $postsPerPage;

// Current page posts
$pagePosts = array_slice($posts, $offset, $postsPerPage);
?>

<div style="background:#fff; padding:30px 15px; font-family: Arial, sans-serif; min-height:100vh;">

    <div style="text-align:center; margin-bottom:40px; border-bottom: 1px solid #eee; padding-bottom: 20px;">
            
                    <a href="/" style="display:inline-block; padding:10px 24px; background:#002366; color:#fff; font-size:16px; font-weight:bold; text-decoration:none; border-radius:50px; margin-bottom:15px; box-shadow:0 4px 6px rgba(0,0,0,0.1);">
                                ðŸ“– Dasabodha
                                        </a>

                                                <h1 style="color:#FF69B4; font-size: 32px; margin: 10px 0 0 0; font-weight: 800; text-transform: uppercase; letter-spacing: 1px;">
                                                            Dashakam <?= $currentPage ?>
                                                                    </h1>
                                                                        </div>

                                                                            <div id="posts-container" style="max-width: 800px; margin: 0 auto;">
                                                                                    <?php foreach($pagePosts as $post): ?>
                                                                                                <div style="background:#FFF9E6; padding:25px 20px; margin-bottom:25px; border-radius:12px; box-shadow:0 4px 10px rgba(0,0,0,0.08); transition:0.3s; border-left: 5px solid #FF69B4;">
                                                                                                                
                                                                                                                                <h2 style="margin-top:0; font-size:24px; margin-bottom:10px; font-weight:bold;">
                                                                                                                                                    <a href="/<?=htmlspecialchars($post['slug'])?>" style="color:#002366; text-decoration:none;">
                                                                                                                                                                            <?=htmlspecialchars($post['title'])?>
                                                                                                                                                                                                </a>
                                                                                                                                                                                                                </h2>

                                                                                                                                                                                                                                <?php 
                                                                                                                                                                                                                                                $meta = !empty($post['meta_description']) ? trim($post['meta_description']) : trim(strip_tags($post['content']));
                                                                                                                                                                                                                                                                $meta = mb_substr($meta, 0, 160); 
                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                <p style="color:#555; font-size:15px; line-height:1.6; margin-bottom:15px;">
                                                                                                                                                                                                                                                                                                                    <?=htmlspecialchars($meta)?>...
                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                    <a href="/<?=htmlspecialchars($post['slug'])?>" style="display:inline-block; font-size:14px; color:#FF69B4; font-weight:bold; text-decoration:none;">
                                                                                                                                                                                                                                                                                                                                                                        Read More â†’
                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                            <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                    <?php if($totalPages > 1): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                        <div style="text-align:center; margin-top:50px; padding-top: 20px; border-top: 1px solid #eee;">
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style="display: flex; justify-content: center; align-items: center; gap: 15px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php if ($currentPage > 1): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="?page=<?= $currentPage - 1 ?>" style="padding: 8px 16px; background: #f0f0f0; color: #333; text-decoration: none; border-radius: 4px; font-size: 14px; font-weight: bold;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    &laquo; Prev
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style="padding: 8px 16px; color: #ccc; font-size: 14px;">&laquo; Prev</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: #FF69B4; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: #fff; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: 50px; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: 50px; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line-height: 50px; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border-radius: 50%; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-size: 22px; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-weight: bold; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        box-shadow: 0 4px 10px rgba(255,105,180,0.4);">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?= $currentPage ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php if ($currentPage < $totalPages): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="?page=<?= $currentPage + 1 ?>" style="padding: 8px 16px; background: #f0f0f0; color: #333; text-decoration: none; border-radius: 4px; font-size: 14px; font-weight: bold;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Next &raquo;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style="padding: 8px 16px; color: #ccc; font-size: 14px;">Next &raquo;</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style="margin-top: 10px; color: #888; font-size: 12px;">Dashakam <?= $currentPage ?> of <?= $totalPages ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php include __DIR__ . '/footer.php'; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
