<?php
// ================================
// Force no cache & UTF-8
// ================================
header('Content-Type: text/html; charset=utf-8');
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
header("Expires: Thu, 01 Jan 1970 00:00:00 GMT");

// ================================
// Determine slug from URL
// ================================
$slug = trim($_GET['slug'] ?? '');
if (!$slug) {
    $slug = trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/');
    }

    // ================================
    // Load posts/pages
    // ================================
    $postsFile = __DIR__.'/data/posts.json';
    $pagesFile = __DIR__.'/data/pages.json';
    $posts = file_exists($postsFile) ? json_decode(file_get_contents($postsFile), true) : [];
    $pages = file_exists($pagesFile) ? json_decode(file_get_contents($pagesFile), true) : [];
    $allItems = array_merge($posts, $pages);

    // Normalize slug
    $slugNormalized = strtolower(trim($slug));
    $slugNormalized = preg_replace('/[^a-z0-9\-]/', '', str_replace(' ', '-', $slugNormalized));

    // ================================
    // Find post/page
    // ================================
    $post = null;
    $type = '';
    foreach($allItems as $p){
        $pslug = strtolower($p['slug'] ?? '');
            $pslug = preg_replace('/[^a-z0-9\-]/', '', str_replace(' ', '-', $pslug));
                if($pslug === $slugNormalized && ($p['status'] ?? 'public') === 'public'){
                        $post = $p;
                                $type = array_search($p, $posts) !== false ? 'post' : 'page';
                                        break;
                                            }
                                            }

                                            // 404 if not found
                                            if(!$post){
                                                include __DIR__.'/header.php';
                                                    echo "<div style='text-align:center; padding:50px;'>Page not found.</div>";
                                                        include __DIR__.'/footer.php';
                                                            exit;
                                                            }

                                                            // ================================
                                                            // SEO Meta
                                                            // ================================
                                                            $focusKeyword = htmlspecialchars($post['focus_keyword'] ?? '');
                                                            $metaDescription = htmlspecialchars(substr(strip_tags($post['meta_description'] ?? $post['content']),0,160));
                                                            $metaKeywords = htmlspecialchars($post['meta_keywords'] ?? $focusKeyword);

                                                            // ================================
                                                            // Track views
                                                            // ================================
                                                            $viewsFile = __DIR__.'/data/views.json';
                                                            $allViews = file_exists($viewsFile) ? json_decode(file_get_contents($viewsFile), true) : [];
                                                            if(!isset($allViews[$slugNormalized])) $allViews[$slugNormalized] = 0;
                                                            $allViews[$slugNormalized]++;
                                                            file_put_contents($viewsFile, json_encode($allViews, JSON_PRETTY_PRINT));
                                                            $viewCount = $allViews[$slugNormalized];

                                                            // ================================
                                                            // Likes (only posts)
                                                            // ================================
                                                            $likeCount = 0;
                                                            if($type==='post'){
                                                                $likesFile = __DIR__.'/data/likes.json';
                                                                    $allLikes = file_exists($likesFile) ? json_decode(file_get_contents($likesFile), true) : [];
                                                                        if(!isset($allLikes[$slugNormalized])) $allLikes[$slugNormalized] = 0;

                                                                            if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['like_button'])){
                                                                                    $allLikes[$slugNormalized]++;
                                                                                            file_put_contents($likesFile, json_encode($allLikes, JSON_PRETTY_PRINT));
                                                                                                    header("Location: /".$slugNormalized);
                                                                                                            exit;
                                                                                                                }
                                                                                                                    $likeCount = $allLikes[$slugNormalized];
                                                                                                                    }

                                                                                                                    // ================================
                                                                                                                    // Comments (only posts)
                                                                                                                    // ================================
                                                                                                                    $commentsFile = __DIR__.'/data/comments.json';
                                                                                                                    $allComments = file_exists($commentsFile) ? json_decode(file_get_contents($commentsFile), true) : [];

                                                                                                                    if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['comment_submit']) && $type==='post'){
                                                                                                                        $name = trim($_POST['name'] ?? '');
                                                                                                                            $email = trim($_POST['email'] ?? '');
                                                                                                                                $commentText = trim($_POST['comment'] ?? '');
                                                                                                                                    if($name && filter_var($email, FILTER_VALIDATE_EMAIL) && $commentText){
                                                                                                                                            $allComments[] = [
                                                                                                                                                        'slug' => $slugNormalized,
                                                                                                                                                                    'name' => htmlspecialchars($name),
                                                                                                                                                                                'email' => htmlspecialchars($email),
                                                                                                                                                                                            'comment' => nl2br(htmlspecialchars($commentText)),
                                                                                                                                                                                                        'created' => date('Y-m-d H:i:s')
                                                                                                                                                                                                                ];
                                                                                                                                                                                                                        file_put_contents($commentsFile, json_encode($allComments, JSON_PRETTY_PRINT));
                                                                                                                                                                                                                                header("Location: /".$slugNormalized);
                                                                                                                                                                                                                                        exit;
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            $postComments = array_filter($allComments, fn($c)=>($c['slug']??'')===$slugNormalized);

                                                                                                                                                                                                                                            // ================================
                                                                                                                                                                                                                                            // Include header
                                                                                                                                                                                                                                            // ================================
                                                                                                                                                                                                                                            include __DIR__.'/header.php';
                                                                                                                                                                                                                                            ?>

                                                                                                                                                                                                                                            <!DOCTYPE html>
                                                                                                                                                                                                                                            <html lang="en">
                                                                                                                                                                                                                                            <head>
                                                                                                                                                                                                                                            <meta charset="UTF-8">
                                                                                                                                                                                                                                            <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                                                                                                                                                                            <title><?php echo htmlspecialchars($post['title']); ?></title>
                                                                                                                                                                                                                                            <meta name="description" content="<?php echo $metaDescription; ?>">
                                                                                                                                                                                                                                            <meta name="keywords" content="<?php echo $metaKeywords; ?>">
                                                                                                                                                                                                                                            <meta name="focus-keyword" content="<?php echo $focusKeyword; ?>">

                                                                                                                                                                                                                                            <!-- Styles -->
                                                                                                                                                                                                                                            <style>
                                                                                                                                                                                                                                            .post-title-box {
                                                                                                                                                                                                                                                background:#FFD966;
                                                                                                                                                                                                                                                    padding:15px;
                                                                                                                                                                                                                                                        font-size:24px;
                                                                                                                                                                                                                                                            font-weight:bold;
                                                                                                                                                                                                                                                                text-align:center;
                                                                                                                                                                                                                                                                    margin-bottom:20px;
                                                                                                                                                                                                                                                                        border-radius:5px;
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                        .share-buttons button {
                                                                                                                                                                                                                                                                            margin-right:5px;
                                                                                                                                                                                                                                                                                padding:8px 12px;
                                                                                                                                                                                                                                                                                    border:none;
                                                                                                                                                                                                                                                                                        border-radius:4px;
                                                                                                                                                                                                                                                                                            cursor:pointer;
                                                                                                                                                                                                                                                                                                font-weight:bold;
                                                                                                                                                                                                                                                                                                    font-size:14px;
                                                                                                                                                                                                                                                                                                        color:white;
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                        .share-buttons input {
                                                                                                                                                                                                                                                                                                            width:60%;
                                                                                                                                                                                                                                                                                                                padding:5px;
                                                                                                                                                                                                                                                                                                                    margin-right:5px;
                                                                                                                                                                                                                                                                                                                        border-radius:4px;
                                                                                                                                                                                                                                                                                                                            border:1px solid #ccc;
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                            .comment-box {margin-top:30px;}
                                                                                                                                                                                                                                                                                                                            .comment-box input, .comment-box textarea {width:100%; padding:8px; margin:5px 0;}
                                                                                                                                                                                                                                                                                                                            </style>
                                                                                                                                                                                                                                                                                                                            </head>
                                                                                                                                                                                                                                                                                                                            <body>

                                                                                                                                                                                                                                                                                                                            <div style="padding:15px; background:#FFF9E6; min-height:100vh; font-family:Arial, sans-serif; max-width:800px; margin:0 auto; box-sizing:border-box;">

                                                                                                                                                                                                                                                                                                                                <!-- Post title -->
                                                                                                                                                                                                                                                                                                                                    <div class="post-title-box"><?php echo htmlspecialchars($post['title']); ?></div>

                                                                                                                                                                                                                                                                                                                                        <!-- Post content -->
                                                                                                                                                                                                                                                                                                                                            <div class="post-content">
                                                                                                                                                                                                                                                                                                                                                    <?php echo $post['content']; ?>
                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                            <!-- Likes and views -->
                                                                                                                                                                                                                                                                                                                                                                <div style="margin-top:15px;">
                                                                                                                                                                                                                                                                                                                                                                        <form method="POST" style="display:inline;">
                                                                                                                                                                                                                                                                                                                                                                                    <button name="like_button">ðŸ‘ Like (<?php echo $likeCount; ?>)</button>
                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                    &nbsp;&nbsp;Views: <?php echo $viewCount; ?>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                            <!-- Share buttons -->
                                                                                                                                                                                                                                                                                                                                                                                                                <div class="share-buttons" style="margin-top:15px;">
                                                                                                                                                                                                                                                                                                                                                                                                                        <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                $postUrl = "https://".$_SERVER['HTTP_HOST']."/".urlencode($slugNormalized);
                                                                                                                                                                                                                                                                                                                                                                                                                                        $shareText = urlencode($post['title'].' '.$postUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onclick="window.open('https://api.whatsapp.com/send?text=<?php echo $shareText; ?>','_blank')" style="background:#25D366;">WhatsApp</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($postUrl); ?>','_blank')" style="background:#3b5998;">Facebook</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onclick="window.open('https://twitter.com/intent/tweet?text=<?php echo $shareText; ?>','_blank')" style="background:#1DA1F2;">Twitter</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onclick="window.open('https://t.me/share/url?url=<?php echo urlencode($postUrl); ?>&text=<?php echo urlencode($post['title']); ?>','_blank')" style="background:#0088cc;">Telegram</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="text" value="<?php echo $postUrl; ?>" readonly id="copyUrl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onclick="document.getElementById('copyUrl').select(); document.execCommand('copy'); alert('URL copied!')" style="background:#666;">Copy URL</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <!-- Comments -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="comment-box">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>Comments (<?php echo count($postComments); ?>)</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php foreach($postComments as $c): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style="border-bottom:1px solid #ccc; margin-bottom:10px; padding-bottom:5px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong><?php echo htmlspecialchars($c['name']); ?></strong> (<?php echo $c['created']; ?>)<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php echo $c['comment']; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endforeach; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <form method="POST">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="text" name="name" placeholder="Your Name" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="email" name="email" placeholder="Your Email" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <textarea name="comment" rows="4" placeholder="Write a comment..." required></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit" name="comment_submit">Submit Comment</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Include footer and copy protection
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                include __DIR__.'/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                include __DIR__ . '/protect.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
